# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
