# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 23:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_auto_20180910_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='T\xedtulo', max_length=200)),
                ('descricao', models.CharField(default='Descri\xe7\xe3o', max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postagem/')),
                ('descricao', models.CharField(default='Descri\xe7\xe3o', max_length=200)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo_post', models.CharField(choices=[('Artigo', 'Artigo'), ('Destaque da Semana', 'Destaque da Semana'), ('Editorial', 'Editorial'), ('Cursos e Eventos', 'Cursos e Eventos')], max_length=25)),
            ],
        ),
    ]
